<script setup>
import { onMounted, ref } from "vue";
import { createPricingRule, deletePricingRule, fetchPricingRules, previewPricingRule, updatePricingRule } from "../api";

const rules = ref([]); const loading = ref(true); const error = ref(""); const message = ref(""); const preview = ref([]); const previewing = ref(null);
function editable(item = {}) { return { id: item.id || null, name: item.name || "", provider: item.provider || "", model_pattern: item.model_pattern || "", match_type: item.match_type || "glob", input_price_cny: item.input_price_cny ?? "0", output_price_cny: item.output_price_cny ?? "0", cache_read_price_cny: item.cache_read_price_cny ?? "0", cache_write_price_cny: item.cache_write_price_cny ?? "0", input_includes_cache: Boolean(item.input_includes_cache), priority: Number(item.priority || 0), enabled: item.enabled !== 0 && item.enabled !== false, built_in: Boolean(item.built_in), source_note: item.source_note || "", saving: false }; }
async function refresh() { loading.value = true; try { rules.value = ((await fetchPricingRules()).items || []).map(editable); error.value = ""; } catch (exc) { error.value = exc?.response?.data?.detail || "价格规则加载失败"; } finally { loading.value = false; } }
function add() { rules.value.unshift(editable({ priority: 100, enabled: true })); }
function payload(item) { return { name: item.name, provider: item.provider || null, model_pattern: item.model_pattern, match_type: item.match_type, input_price_cny: String(item.input_price_cny || 0), output_price_cny: String(item.output_price_cny || 0), cache_read_price_cny: String(item.cache_read_price_cny || 0), cache_write_price_cny: String(item.cache_write_price_cny || 0), input_includes_cache: item.input_includes_cache, priority: Number(item.priority || 0), enabled: item.enabled, source_note: item.source_note || null }; }
async function save(item, index) { item.saving = true; error.value = ""; try { const saved = item.id ? await updatePricingRule(item.id, payload(item)) : await createPricingRule(payload(item)); rules.value[index] = editable(saved); message.value = "价格规则已保存，仅影响后续请求。"; } catch (exc) { error.value = exc?.response?.data?.detail || "价格规则保存失败"; } finally { item.saving = false; } }
async function remove(item, index) { if (item.id && !window.confirm(`删除价格规则“${item.name}”？历史费用快照不会被删除。`)) return; try { if (item.id) await deletePricingRule(item.id); rules.value.splice(index, 1); message.value = "规则已删除，历史费用保持不变。"; } catch (exc) { error.value = exc?.response?.data?.detail || "规则删除失败"; } }
async function showPreview(item) { previewing.value = item; preview.value = []; try { preview.value = (await previewPricingRule(payload(item))).items || []; } catch (exc) { error.value = exc?.response?.data?.detail || "匹配预览失败"; } }
onMounted(refresh);
</script>
<template><section class="pricing-section"><div class="section-heading"><div><h2>模型价格</h2><p>人民币元/百万 Token；价格修改只影响后续请求。</p></div><button type="button" @click="add">＋ 新增规则</button></div><div v-if="message" class="notice success">{{ message }}</div><div v-if="error" class="notice error">{{ error }}</div><div v-if="loading" class="empty">正在加载价格规则…</div><article v-for="(item,index) in rules" :key="item.id || `new-${index}`" class="rule-card"><header><div><strong>{{ item.name || '新价格规则' }}</strong><span v-if="item.built_in">内置</span><i :class="{ off: !item.enabled }">{{ item.enabled ? '启用' : '停用' }}</i></div><div><button type="button" class="plain" @click="showPreview(item)">预览匹配</button><button type="button" class="danger" @click="remove(item,index)">删除</button></div></header><div class="rule-grid"><label><span>规则名称</span><input v-model.trim="item.name" /></label><label><span>限定 Provider（可选）</span><input v-model.trim="item.provider" placeholder="留空表示全部" /></label><label><span>模型匹配</span><input v-model.trim="item.model_pattern" placeholder="例如 gpt-5*" /></label><label><span>匹配方式</span><select v-model="item.match_type"><option value="exact">精确</option><option value="glob">通配符</option></select></label><label><span>Input 单价</span><input v-model="item.input_price_cny" type="number" min="0" step="0.000001" /></label><label><span>Output 单价</span><input v-model="item.output_price_cny" type="number" min="0" step="0.000001" /></label><label><span>Cache Read 单价</span><input v-model="item.cache_read_price_cny" type="number" min="0" step="0.000001" /></label><label><span>Cache Write 单价</span><input v-model="item.cache_write_price_cny" type="number" min="0" step="0.000001" /></label><label><span>优先级</span><input v-model.number="item.priority" type="number" min="-10000" max="10000" /></label><label><span>来源说明</span><input v-model.trim="item.source_note" /></label></div><div class="flags"><label><input v-model="item.enabled" type="checkbox" />启用规则</label><label><input v-model="item.input_includes_cache" type="checkbox" />Input Token 已包含缓存 Token（OpenAI 风格）</label><button type="button" :disabled="item.saving" @click="save(item,index)">{{ item.saving ? '保存中…' : '保存规则' }}</button></div></article><div v-if="!rules.length && !loading" class="empty">尚无价格规则</div><div v-if="previewing" class="preview"><header><div><h3>匹配预览：{{ previewing.name || '未命名规则' }}</h3><p>仅预览当前历史模型，不会重新计算费用。</p></div><button type="button" @click="previewing=null">×</button></header><div v-if="preview.length" class="preview-list"><div v-for="item in preview" :key="`${item.provider}:${item.model}`"><b>{{ item.model }}</b><span>{{ item.provider }}</span><em>{{ item.requests }} 次 · {{ item.total_tokens.toLocaleString('zh-CN') }} Token</em></div></div><div v-else class="empty small">没有匹配到已有模型</div></div></section></template>
<style scoped>.pricing-section{margin-top:24px}.section-heading{display:flex;align-items:center;justify-content:space-between;gap:15px;margin-bottom:14px}.section-heading h2{margin:0;color:#101828;font-size:18px}.section-heading p{margin:5px 0 0;color:#7b879b;font-size:11px}.section-heading>button,.flags>button{height:38px;border:0;border-radius:7px;padding:0 14px;color:#fff;background:#2476f5}.notice{margin-bottom:10px;padding:10px 13px;border-radius:8px;font-size:11px}.notice.success{color:#087a55;background:#effbf6}.notice.error{color:#b42318;background:#fff1f1}.rule-card{margin-bottom:12px;padding:17px;border:1px solid #e6ebf2;border-radius:10px;background:#fff;box-shadow:0 2px 8px #1018280a}.rule-card header{display:flex;justify-content:space-between;gap:12px;margin-bottom:15px}.rule-card header>div{display:flex;align-items:center;gap:8px}.rule-card header strong{color:#101828;font-size:14px}.rule-card header span,.rule-card header i{padding:3px 7px;border-radius:99px;color:#1769ef;background:#edf4ff;font-size:9px;font-style:normal}.rule-card header i{color:#087a55;background:#eaf9f2}.rule-card header i.off{color:#667085;background:#f2f4f7}.rule-card header button{border:0;background:transparent;font-size:11px}.plain{color:#1769ef}.danger{color:#d92d20}.rule-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.rule-grid label{display:grid;gap:6px;color:#667085;font-size:10px}.rule-grid input,.rule-grid select{height:37px;min-width:0;border:1px solid #dfe5ed;border-radius:7px;padding:0 10px;color:#344054;background:#fff}.flags{display:flex;align-items:center;gap:18px;margin-top:14px;color:#667085;font-size:11px}.flags label{display:flex;align-items:center;gap:6px}.flags button{margin-left:auto}.empty{min-height:100px;display:grid;place-items:center;color:#98a2b3;font-size:11px}.empty.small{min-height:70px}.preview{position:fixed;inset:10% 10%;z-index:120;overflow:auto;padding:20px;border:1px solid #dfe5ed;border-radius:12px;background:#fff;box-shadow:0 20px 60px #10182835}.preview header{display:flex;justify-content:space-between}.preview h3{margin:0;color:#101828}.preview p{color:#7b879b;font-size:11px}.preview header button{width:32px;height:32px;border:0;border-radius:6px;font-size:22px}.preview-list{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.preview-list>div{display:grid;gap:4px;padding:10px;border-radius:7px;background:#f7f9fc;font-size:11px}.preview-list span,.preview-list em{color:#667085;font-style:normal}@media(max-width:900px){.rule-grid{grid-template-columns:repeat(2,1fr)}.preview-list{grid-template-columns:1fr 1fr}}@media(max-width:560px){.rule-grid{grid-template-columns:1fr}.flags{align-items:flex-start;flex-direction:column}.flags button{width:100%;margin:0}.preview{inset:4%}.preview-list{grid-template-columns:1fr}}</style>
