<script setup>
import { computed, nextTick, onBeforeUnmount, onMounted, ref, watch } from "vue";
import * as echarts from "echarts";
import ApiStateBanner from "../components/ApiStateBanner.vue";
import CostBreakdown from "../components/CostBreakdown.vue";
import ModelIcon from "../components/ModelIcon.vue";
import { fetchCostModels, fetchCostProviders, fetchCostSummary, fetchCostTrend, fetchUnpricedModels } from "../api";

const props = defineProps({ autoRefresh: { type: Boolean, default: true }, refreshInterval: { type: Number, default: 10000 } });
const period = ref("month"); const today = ref({}); const month = ref({}); const current = ref({});
const trend = ref([]); const models = ref([]); const providers = ref([]); const unpriced = ref([]);
const error = ref(""); const updatedAt = ref(""); const loading = ref(true); const chartEl = ref(null); const unpricedBannerVisible = ref(true);
let chart = null; let timer = null;
const coverageTone = computed(() => Number(current.value.coverage_rate || 0) >= 100 ? "good" : "warn");
function money(value) { const amount = Number(value || 0) / 1_000_000; return `¥${amount < .01 ? amount.toFixed(6) : amount.toFixed(2)}`; }
function fmt(value) { return (Number(value) || 0).toLocaleString("zh-CN"); }
function updateChart() { chart?.setOption({ color: ["#2476f5"], tooltip: { trigger: "axis", valueFormatter: value => money(value) }, grid: { left: 18, right: 18, top: 24, bottom: 28, containLabel: true }, xAxis: { type: "category", boundaryGap: false, data: trend.value.map(item => item.bucket.slice(5).replace("T", " ")), axisLabel: { hideOverlap: true, color: "#7b879b" } }, yAxis: { type: "value", axisLabel: { color: "#7b879b", formatter: value => money(value) }, splitLine: { lineStyle: { color: "#edf1f6", type: "dashed" } } }, series: [{ name: "费用", type: "line", smooth: true, showSymbol: false, areaStyle: { color: "rgba(36,118,245,.12)" }, data: trend.value.map(item => item.total_cost_micros) }] }, true); }
async function refresh() { loading.value = true; try { const [todayData, monthData, currentData, trendData, modelData, providerData, unpricedData] = await Promise.all([fetchCostSummary("today"), fetchCostSummary("month"), fetchCostSummary(period.value), fetchCostTrend(period.value), fetchCostModels(period.value, 10), fetchCostProviders(period.value, 10), fetchUnpricedModels(period.value)]); today.value = todayData; month.value = monthData; current.value = currentData; trend.value = trendData.items || []; models.value = modelData.items || []; providers.value = providerData.items || []; unpriced.value = unpricedData.items || []; error.value = ""; updatedAt.value = new Date().toLocaleTimeString("zh-CN", { hour12: false }); await nextTick(); updateChart(); } catch (exc) { error.value = exc?.response?.data?.detail || "费用数据加载失败"; } finally { loading.value = false; } }
function configureTimer() { clearInterval(timer); timer = props.autoRefresh ? setInterval(refresh, props.refreshInterval) : null; }
function resize() { chart?.resize(); }
onMounted(() => { chart = echarts.init(chartEl.value); window.addEventListener("resize", resize); refresh(); configureTimer(); });
onBeforeUnmount(() => { clearInterval(timer); chart?.dispose(); window.removeEventListener("resize", resize); });
watch(period, refresh); watch(() => [props.autoRefresh, props.refreshInterval], configureTimer); defineExpose({ refresh });
</script>
<template><div class="costs-page" :class="{ loading }"><div class="page-heading"><div><h1>费用分析</h1><p>基于请求发生时保存的人民币价格快照估算</p></div><select v-model="period"><option value="today">今日</option><option value="month">本月</option><option value="24h">最近24小时</option><option value="7d">最近7天</option><option value="30d">最近30天</option></select></div><ApiStateBanner :error="error" :updated-at="updatedAt" /><div v-if="current.unpriced_requests && unpricedBannerVisible" class="unpriced-banner"><span>有 {{ fmt(current.unpriced_requests) }} 条请求尚未定价，共 {{ fmt(current.unpriced_tokens) }} Token；费用暂记为 ¥0。</span><button type="button" aria-label="关闭未定价提示" title="关闭" @click="unpricedBannerVisible = false">×</button></div><section class="cards"><article><span>今日费用</span><b>{{ money(today.total_cost_micros) }}</b><small>{{ fmt(today.priced_requests) }} 条已定价请求</small></article><article><span>本月费用</span><b>{{ money(month.total_cost_micros) }}</b><small>{{ fmt(month.requests) }} 条请求</small></article><article><span>当前周期费用</span><b>{{ money(current.total_cost_micros) }}</b><small>{{ period }}</small></article><article><span>定价覆盖率</span><b :class="coverageTone">{{ Number(current.coverage_rate || 0).toFixed(1) }}%</b><small>{{ fmt(current.unpriced_requests) }} 条未定价</small></article></section><section class="main-grid"><article class="panel trend-panel"><div class="heading"><h2>费用趋势</h2><span>{{ money(current.total_cost_micros) }}</span></div><div ref="chartEl" class="chart"></div></article><article class="panel"><div class="heading"><h2>费用构成</h2></div><CostBreakdown :summary="current" /></article></section><section class="rank-grid"><article class="panel"><div class="heading"><h2>模型费用排行</h2><RouterLink to="/models">模型分析</RouterLink></div><div v-for="item in models" :key="item.model" class="row"><b class="model-name"><ModelIcon :model="item.model" :size="26" />{{ item.model }}</b><span>{{ money(item.total_cost_micros) }}</span><small>{{ fmt(item.total_tokens) }} Token</small></div><div v-if="!models.length" class="empty">暂无费用数据</div></article><article class="panel"><div class="heading"><h2>Provider 费用排行</h2><RouterLink to="/providers">Provider 分析</RouterLink></div><div v-for="item in providers" :key="item.provider" class="row"><b>{{ item.provider }}</b><span>{{ money(item.total_cost_micros) }}</span><small>{{ fmt(item.requests) }} 次请求</small></div><div v-if="!providers.length" class="empty">暂无费用数据</div></article></section><section v-if="unpriced.length" class="panel unpriced"><div class="heading"><h2>未定价模型</h2><RouterLink to="/settings">配置价格</RouterLink></div><div class="unpriced-grid"><div v-for="item in unpriced" :key="`${item.provider}:${item.model}`"><b class="model-name"><ModelIcon :model="item.model" :provider="item.provider" :size="26" />{{ item.model }}</b><span>{{ item.provider }}</span><em>{{ fmt(item.requests) }} 次 · {{ fmt(item.total_tokens) }} Token</em></div></div></section></div></template>
<style scoped>.costs-page{max-width:1540px;margin:0 auto;color:#475467;transition:opacity .2s}.loading{opacity:.75}.page-heading{min-height:70px;display:flex;justify-content:space-between}.page-heading h1{margin:0;color:#101828;font-size:22px}.page-heading p{margin:7px 0;color:#7b879b;font-size:13px}.page-heading select{height:38px;border:1px solid #dfe5ed;border-radius:7px;padding:0 11px;color:#344054;background:#fff}.unpriced-banner{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:12px;padding:8px 10px 8px 14px;border:1px solid #fedf89;border-radius:8px;color:#93370d;background:#fffaeb;font-size:12px}.unpriced-banner button{width:26px;height:26px;flex:none;border:0;border-radius:5px;padding:0;color:#93370d;background:transparent;font-size:20px;line-height:1;cursor:pointer}.unpriced-banner button:hover{background:#fef0c7}.cards{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-bottom:14px}.cards article,.panel{border:1px solid #e6ebf2;border-radius:10px;background:#fff;box-shadow:0 2px 8px #1018280a}.cards article{min-height:105px;display:grid;align-content:center;gap:6px;padding:17px}.cards span,.cards small{color:#667085;font-size:11px}.cards b{color:#101828;font-size:24px}.cards b.warn{color:#d97706}.cards b.good{color:#087a55}.main-grid{display:grid;grid-template-columns:1.7fr .7fr;gap:14px;margin-bottom:14px}.panel{padding:17px}.heading{display:flex;justify-content:space-between;gap:12px;margin-bottom:14px}.heading h2{margin:0;color:#101828;font-size:15px}.heading span{color:#667085;font-size:12px}.heading a{color:#1769ef;font-size:11px;text-decoration:none}.chart{height:310px}.rank-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin-bottom:14px}.row{display:grid;grid-template-columns:1fr auto auto;gap:12px;align-items:center;min-height:44px;border-bottom:1px solid #edf1f6;font-size:11px}.row b{overflow:hidden;color:#344054;text-overflow:ellipsis}.model-name{display:flex;align-items:center;gap:8px}.row span{color:#101828;font-weight:700}.row small{color:#98a2b3}.empty{height:120px;display:grid;place-items:center;color:#98a2b3;font-size:11px}.unpriced-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:9px}.unpriced-grid>div{display:grid;gap:4px;padding:10px;border-radius:7px;background:#fff9ed;font-size:11px}.unpriced-grid b{color:#7a2e0e}.unpriced-grid span{color:#667085}.unpriced-grid em{color:#b54708;font-style:normal}@media(max-width:1000px){.cards{grid-template-columns:repeat(2,1fr)}.main-grid,.rank-grid{grid-template-columns:1fr}}@media(max-width:620px){.unpriced-grid{grid-template-columns:1fr}.row small{display:none}}</style>
